version: '3'

services:
  nginx:
    container_name: nginx
    image: nginx:1.15-alpine
    restart: unless-stopped
    volumes:
      - ./data/nginx:/etc/nginx/conf.d
      - ./data/cert:/etc/letsencrypt/live
      - ./data/certbot/www:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
  certbot:
    image: certbot/certbot
    restart: unless-stopped
    volumes:
      - ./data/cert:/etc/letsencrypt/live
      - ./data/certbot/www:/var/www/certbot
    networks:
          - back_network

  nexus_registry:
    image: sonatype/nexus
    environment:
      - DOMAIN_URL=yourdomain.com
      - DOMAIN_EMAIL=youremail@mail.com
    volumes:
      - "./data/nexus:/sonatype-work"
    networks:
      - back_network

networks:
  back_network:
    driver: bridge